export const GET_EVENTS_BEGIN = "GET_EVENTS_BEGIN";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";

export const SAVE_EVENT_BEGIN = "SAVE_EVENT_BEGIN";
export const SAVE_EVENT_SUCCESS = "SAVE_EVENT_SUCCESS";
export const SAVE_EVENT_FAILURE = "SAVE_EVENT_FAILURE";

export const DELETE_EVENT_BEGIN = "DELETE_EVENT_BEGIN";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";

export const CHANGE_TITLE = "CHANGE_TITLE";
export const CHANGE_DATE = "CHANGE_DATE";
export const TOGGLE_DATE_PICKER = "TOGGLE_DATE_PICKER";
